name: PHP Composer

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: drakona/php:7.4-ci

    services:
      db:
        image: mysql:5.7

        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: test

    steps:
      - uses: actions/checkout@v2
      - name: Set correct env file
        run: cp .env.ci .env.local

      - name: Validate composer.json and cmposer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        run: cp .env.ci .env.local
      - uses: action/cache@v2
        with:
          path: vendor
          key: ${{ runner.os}}-php${{ hashFiles('**/composer.lock')}}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Load fixtures
        run: php bin/console doctrine:fixtures:load -n

  analysis:
    runs-on: ubuntu-latest
    container: drakona/php:7.4-ci

    steps:
      - uses: actions/checkout@v2

      - name: Set correct env file
        run: cp .env.ci .env.local

      - name: Install PHP CS Fixer
        run: |
          curl -L https://cs.symfony.com/download/php-cs-fixer-v3.phar -o php-cs-fixer.phar
          chmod a+x ./php-cs-fixer.phar

      - name: Run PHP CS Fixer check
        run: ./php-cs-fixer.phar fix src --dry-run --diff
